# Generated by Django 6.0.2 on 2026-02-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('university', models.CharField(max_length=200)),
                ('source', models.CharField(choices=[('IIT', 'IIT'), ('IVY', 'Ivy League')], max_length=10)),
                ('link', models.URLField(unique=True)),
                ('posted_date', models.DateField(blank=True, null=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
