# Generated by Django 6.0.2 on 2026-02-21 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='opportunity_type',
            field=models.CharField(default='OTHER', max_length=50),
        ),
    ]
