# Generated by Django 6.0.2 on 2026-02-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0002_opportunity_opportunity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
